# Initiation à Python


Le texte que vous êtes en train de lire est contenu dans une cellule de type *Markdown* qui permet un [formattage aisé](https://help.github.com/articles/markdown-basics/) du texte, y compris des formules $\LaTeX$ en ligne comme $\sum\gamma_i^2$ ou en equations séprarées:
$$\frac{\ln \pi}{12}.$$

Un notebook peut donc contenir deux types de cellules:
 - Markdown 
 - Code

Vous pouvez sélectionner le type de cellule dans le menu déroulant de la barre d'outils ci-dessus.  Vous pouvez ajouter des cellules. Les cellules de code s'exécutent en faisant Maj+Entrer (ou en utilisant le bouton "play" à gauche de la cellule dans vscode). Les cellules Markdown se formattent de la même façon et on retourne à l'édition de leur contenu par un double clic.

## Les fonctions

En Python, tout est dans l'indentation

In [1]:
def mafonction(a, b):
    print("Je divise")
    return a/b # indentation de l'intérieur de la fonction = on est toujours dans la fonction
print("fini de définir ma fonction") # indentation de l'extérieur de la fonction donc la fonction est finie

fini de définir ma fonction


In [2]:
mafonction(5,2)

Je divise


2.5

On peut documenter ses propres fonctions.

In [4]:
def mafonction(a, b):
    """Division de a par b"""
    return a/b

In [5]:
mafonction?

Signature: mafonction(a, b)
Docstring: Division de a par b
File:      /tmp/ipykernel_10188/26343411.py
Type:      function


Il est possible d'avoir des arguments par défaut.

In [6]:
def mafonction(a, b=2):
    """Division de a par b"""
    return a/b
print(mafonction(5))
print(mafonction(5,10))

2.5
0.5


In [7]:
mafonction?

Signature: mafonction(a, b=2)
Docstring: Division de a par b
File:      /tmp/ipykernel_10188/2761522841.py
Type:      function


Un peu plus complexe : on imbrique deux indentations et on a 2 arguments avec des valeurs par défaut.

In [8]:
def mafonction(a, b=2, diviser=True):
    """Division de a par b.
    Si on ne divise pas, on retourne a et b""" #on a le droit de passer à la ligne si on a ouvert 3 guillemets
    if diviser:
        return a/b
    else:
        return a,b
print(mafonction(5))
print(mafonction(5, 10))
print(mafonction(5, diviser=False))

2.5
0.5
(5, 2)


## Jouer avec les chaînes de caractères 

### Indexation, sous-chaîne et concaténation

In [10]:
a = "coucou" #definition de l'objet. Pas besoin de donner son type
print(a) #affichage de toute la chaîne de caractères
print(a[0]) #affichage du premier élément. Attention, les indices commencent à 0
print(a[1])
print(a[-1]) #affichage du dernier élément. On utilise des entiers négatifs pour partir de la fin
print(a[1:]) #affichage à partir de l'élément 1
print(a[:3]) #jusqu'à l'élément 3 non inclu. Equivalent mais plus court que a[0:3]
print(a[:-1]) #jusqu'au dernier élément non inclu
print(a[::2]) #tous les 2 éléments. Equivalent mais plus court que a[0:len(a):2]
print(a[1:-1:3]) #à partir de l'élement 1, jusqu'au dernier élément non inclu, tous les 3 éléments

coucou
c
o
u
oucou
cou
couco
cuo
oo


In [ ]:
print("cou" + "cou") #concaténation de deux chaînes de caractères
print("cou" * 2) # répétition 2 fois

### Les boucles

In [ ]:
#premiere boucle for. On itère directement sur les caractères de la chaîne.
for lettre in a:
    print(lettre)
    print("-") # indentation de l'intérieur de la boucle = on est toujours dans la boucle
print("c'est fini") # indentation de l'extérieur de la boucle donc la boucle est finie

In [ ]:
for lettre in a[::-1]:
    print(lettre)

In [ ]:
for i,lettre in enumerate(a): #i est l'indice de l'itération dans la boucle
    print(i,lettre)

In [11]:
for u,v in zip(a, "colibri"): #à chaque tour de boucle on prend une lettre de "coucou" et une lettre de "colibri"
    print(u+v)

cc
oo
ul
ci
ob
ur


### Phrases à trous

In [12]:
b = "Je m'appelle {}."
print(b)
print(b.format("Mathieu"))

Je m'appelle {}.
Je m'appelle Mathieu.


In [13]:
print(a.format("Mathieu"))

coucou


In [14]:
b = "My name is {1}, {0} {1}."
print(b.format("James", "Bond"))

My name is Bond, James Bond.


In [ ]:
b2 = "My name is {nom}, {prenom} {nom}."
print(b2.format(prenom="James", nom="Bond"))

In [15]:
c = "Veuillez charger le fichier acquisition_t{:03d}.txt" #nombre décimal sur 3 chiffres, éventuellement complétés de zéros
print(c.format(5))
print(c.format(23))
print(c.format(328))

Veuillez charger le fichier acquisition_t005.txt
Veuillez charger le fichier acquisition_t023.txt
Veuillez charger le fichier acquisition_t328.txt


Syntaxe complète des [instructions de formattage](https://docs.python.org/3/library/string.html#format-string-syntax), si un jour vous avez envie d'afficher un nombre hexadécimal sur 7 charactères minimum, éventuellement complété avec des symboles livre sterling, ou un nombre flottant avec 2 chiffres significatifs.

On peut aussi obtenir de l'aide sur une méthode d'un objet.

In [16]:
c.format?

Docstring:
S.format(*args, **kwargs) -> str

Return a formatted version of S, using substitutions from args and kwargs.
The substitutions are identified by braces ('{' and '}').
Type:      builtin_function_or_method


In [ ]:
print("Veuillez charger le fichier acquisition_t%03d.txt"%5)

## Listes

In [17]:
l = ["a", "b", 127, 3.14, ["James", "Bond"], "c"]
print(l)
print(l[0])
print(l[1][0])
print(l[0]+l[1].format(l[-2][0], l[-2][1])) # pour "déplier" tous les éléments de la liste l[-2] en tant qu'arguments de la fonction format
#possible d'écrire directement format(*l[-2])
print(l[-1].format(l[2]) + " Mr {}.".format(l[-2][-1]))

['a', 'b', 127, 3.14, ['James', 'Bond'], 'c']
a
b
ab
c Mr Bond.


Il est possible de modifier les éléments d'une liste et même de changer leur type.

In [18]:
l[2] = 12
l[-2][-1] = 3
print(l[-1].format(l[2]) + " Mr {}.".format(l[-2][-1]))

c Mr 3.


In [19]:
l2 = []
for i in range(3):
    l2.append(i**2)
print(l2)

[0, 1, 4]


## tuple

Comme une liste, mais avec des parenthèses au lieu de crochets. Il est interdit de modifier le contenu d'un tuple.

In [ ]:
t = ("a", "b", 127, 3.14, ("James", "Bond"), "c")
print(t)
print(t[0])
print(t[1][0])
print(t[0]+t[1].format(*t[-2]))
print(t[-1].format(t[2]) + " Mr {}.".format(t[-2][-1]))

In [ ]:
tuple(l)

In [ ]:
list(t)

# Librairies

## Import

Toute la librairie

In [ ]:
import os
os.listdir()

Une seule fonction dans la librairie, directement accessible sans avoir à taper `librairie.fonction`

In [ ]:
from os import listdir
listdir()

Marche aussi avec les sous-librairies et les fonctions des sous librairies.

In [ ]:
from os import path #sous-librairie de os
print(path.isfile('Initiation.ipynb'))
from os.path import isfile
print(isfile('Initiation.ipynb'))

La syntaxe, **à éviter en général**, de l'import de tout ce qui est dans une librairie.

```python
from os import *
```

### Numpy : tableaux numériques

In [21]:
import numpy as np #abbréviation du nom de la librairie pour taper 2 lettres au lieu de 5

Quelques fonctions pour créer des tableaux standards.

In [22]:
np.zeros(3), np.ones(2, complex), np.arange(4)

(array([0., 0., 0.]), array([1.+0.j, 1.+0.j]), array([0, 1, 2, 3]))

In [24]:
l = [1,5,7] #liste numérique
print(l)
a = np.array(l) #transformée en tableau numpy
print(a)
b = np.array([1.2, 5, 6]) #les 2 étapes d'un coup
print(b)
print("a est un tableau à {} dimensions de taille {} contenant uniquement des {}".format(a.ndim, a.shape, a.dtype)) 
print("b est un tableau à {} dimensions de taille {} contenant uniquement des {}".format(b.ndim, b.shape, b.dtype)) 

[1, 5, 7]
[1 5 7]
[1.2 5.  6. ]
a est un tableau à 1 dimensions de taille (3,) contenant uniquement des int64
b est un tableau à 1 dimensions de taille (3,) contenant uniquement des float64


Toutes les opérations se font élément par élément, même la multiplication. Pas besoin de point comme en MATLAB. La multiplication matricielle se fait avec `np.matmul`.

In [25]:
print(2 * a)
print(a + b)
print(a * b)
print(a / b)
print(a>2)
print(np.exp(a))

[ 2 10 14]
[ 2.2 10.  13. ]
[ 1.2 25.  42. ]
[0.83333333 1.         1.16666667]
[False  True  True]
[   2.71828183  148.4131591  1096.63315843]


Le type des tableaux s'adapte automatiquement si besoin

In [ ]:
c = a + b
print(c.dtype)
d = np.array([1,2,3])/a #division réélle, bseoin de passer en flottant, même si les tableaux ne contiennent que des entiers
print(d)
print(d.dtype)
e = np.array([1,2,3])//a #division Euclidienne, on reste en entiers
print(e)
print(e.dtype)

Tableaux en 2 ou plus dimensions en imbriquant des listes

In [ ]:
a = np.array([[1,2,3],[7,4,5]])
print("a est un tableau à {} dimensions de taille {} contenant uniquement des {}".format(a.ndim, a.shape, a.dtype)) 

In [ ]:
print(a)
print(a.T)

De nombreuses possibilités d'indexation

In [ ]:
print(a[0,1])
print(a[0])
print(a[0][1])
print(a[:,0])
print(a[::-1,[0, 2]])
print(a[a>2])

Possible de faire des opération si l'un des tableaux est de dimension plus faible et si la forme de celui-ci correspond à la fin de la forme de l'autre tableau.

In [ ]:
print(a)
print(b)
print(a.shape, b.shape)
a + b

In [ ]:
a.T + b

In [ ]:
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

### Matplotlib

Graphiques, lecture et écriture d'images

In [ ]:
from matplotlib import pylab as plt
#permet la modification en live des figures dans le notebook
%matplotlib

In [ ]:
plt.plot(b)

Pour un document à montrer, on préfère avoir des figures directement insérée dedans en tant qu'image.

In [ ]:
%matplotlib inline
plt.plot(b)

Mais on ne peut plus sélectionner les données directement, pas très pratique pour l'analyse de données. On revient donc en mode normal (fenêtre externe).

In [ ]:
%matplotlib

In [ ]:
plt.figure('Evolution de b') # création ou sélection d'une figure. La figure est nommée, ce qui est plus explicite qu'une numérotation
plt.clf() # on efface la figure courante
plt.plot(b)
plt.yscale('log')
plt.ylabel('b')
plt.xlabel(r'$\gamma_c$') # pas de caractères spéciaux, donc on a le droit de mettre des antislash pour les commandes LaTeX
plt.savefig('mafig.pdf')

### Numpy et l'algèbre linéaire

 Définir les matrices suivantes.  
	$M_1=\left( \begin{array}
		{ccccc} 5 & 6 & 7 & 8 & 9 \end{array} \right),  
	M_2=\left( \begin{array}
		{ccccc} 1 & 1 & 1 & 1 & 1 \end{array} \right),    
	M_3=\left( \begin{array}
		{c}	1 \\
		2 \\
		3 \end{array} \right),
	M_4=\left( \begin{array}{ccc}
		1 & 2 & 4 \\
		-1 & 2 & 3 \\
		1 & 8 & 9 \end{array} \right).
	$

 
Construire les matrices suivantes à partir des matrices $M_1, \; M_2, \; M_3, \; M_4$ définies précédemment :  
	$
	M_5=\left( \begin{array}
		{cccccc} 5 & 6 & 7 & 8 & 9 & 10 \end{array} \right)
	$   
	$
	M_6=\left( \begin{array}
		{cccccccccc} 1 & 1 & 1 & 1 & 1 & 5 & 6 & 7 & 8 & 9 \end{array} \right)
	$  
	$
	M_7=\left( \begin{array}{ccccc}
		5 & 6 & 7 & 8 & 9 \\
		1 & 1 & 1 & 1 & 1.
	\end{array} \right)
	$  
	$
	M_8=\left( \begin{array}{c}
		1 \\
		2 \\
		3 \\
		4
	\end{array} \right) 
	$  
	$
	M_9=\left( \begin{array}{cccc}
		1 & 2 & 4 & 1 \\
		-1 & 2 & 3 & 7 \\
		1 & 8 & 9 & 4
	\end{array} \right)
	$  
	$ 
	M_{10}=\left( \begin{array}{cccc}
		1 & 2 & 4 & 1 \\
		-1 & 2 & 3 & 2 \\
		1 & 8 & 9 & 3
	\end{array} \right)
	$

1. $M_{12}$ : Ajouter $2$ au début de $M_2$.
2. $M_{13}$ : Ajouter $8$ en bas de $M_3$ et $9$ en haut de $M_3$.
3. $M_{14}$ : Supprimer la $2$ème ligne de $M_4$. _On pourra utiliser l'instruction **np.delete()**_
4. $M_{15}$ : Supprimer la $1$ère et la $3$ème cases de $M_1$.
5. $M_{16}$ : Mettre $8$ dans la $1$ère et la $3$ème cases de $M_1$.
6. $M_{17}$ : Supprimer la $2$ème colonne de $M_4$.


In [ ]:
M12=

Sans utiliser les fonctions **abs**, **pow** ou encore l'opérateur **? :
1. Définir une fonction **absolue** prenant en entrée un entier et retournant sa valeur absolue. (On ne demande pas de vérifier que le paramètre passé à la fonction est un entier).
2. Définir une fonction **fact** prenant en entrée un entier positif et retournant sa factorielle définie par $$n !\, = \prod_{i=1}^ni=n(n-1)(n-2)\cdots1$$.
3. Définir une fonction **puissance** prenant deux arguments $x$ et $n$ et retournant $x^n$. (On supposera que $n$ est un entier positif, et on posera $x^{0}=1$ pour tout réel $x$). 
4. Définir les deux fonctions précédentes de manières itérative et récursive. 

In [ ]:
def absolue(i):
    
def fact(n):
    
def puissance(x,n):

Dans chacun cas suivant, écrire une fonction qui résout le problème posé sans utiliser les fonctions prédéfinies de python.
1. Écrire une fonction _transpose_ qui prend en entrée une matrice $A$ de taille $p\times n$ et retourne une matrice $B$ égale à la transposée $~^tA$ de $A$.
2. Écrire une fonction _diagonale_ qui prend en entrée une matrice $A$ de taille $p\times n$ et retourne une matrice  $B$ de même taille dont les coefficients de la diagonale sont égaux à ceux de $A$ et les autres son nuls.
3. Ecrire une fonction _trace_ qui prend en entrée une matrice $A$ de taille $n \times n$ et retourne la somme des valeurs de la diagonale principale.
4. Ecrire une fonction _valeurmax_ qui prend en entrée une matrice $A$ de taille $n \times p$ quelconque et retourne la valeur maximale des coefficients de $A$ et sa position  (i_max,j_max) dans la matrice $A$.
5. Écrire une fonction _produitscalaire_ qui prend en paramètres d'entrée un vecteur ligne $A$ et un vecteur colonne $B$, de tailles $1\times l$ et $l\times 1$, et retourne leur produit scalaire.
6. Écrire une fonction _produitmatrice_ qui prend en entrée deux matrices $A$ et $B$, de tailles $m\times p$ et $k\times n$, et retourne leur produit matriciel s'il existe ou un message d'erreur dans le cas contraire. 


In [ ]:
def transpose(A):
    
def diagonale(A):
    
def trace(A):
    
def valeurmax(A):
    
def produitscalaire(A,B):
    
def produitmatrice(A,B):